//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BF1MarneTools.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BF1MarneTools.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 EA账号邮箱 的本地化字符串。
        /// </summary>
        public static string AccountWin_Email {
            get {
                return ResourceManager.GetString("AccountWin_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入拥有战地1游戏的EA账号的邮箱 的本地化字符串。
        /// </summary>
        public static string AccountWin_EmailHint {
            get {
                return ResourceManager.GetString("AccountWin_EmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认账号 的本地化字符串。
        /// </summary>
        public static string AccountWin_EnterAccount {
            get {
                return ResourceManager.GetString("AccountWin_EnterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示：请输入任意拥有战地1游戏的EA账号邮箱和密码，即使这个账号被协议6封禁，或者被EAAC或FF封禁。只需要账号拥有战地1游戏即可，无论游戏版本，主要是为了让EA下发战地1的「Denuvo加密」许可证，否则无法启动游戏。 的本地化字符串。
        /// </summary>
        public static string AccountWin_Note {
            get {
                return ResourceManager.GetString("AccountWin_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EA账号密码 的本地化字符串。
        /// </summary>
        public static string AccountWin_Password {
            get {
                return ResourceManager.GetString("AccountWin_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入拥有战地1游戏的EA账号的密码 的本地化字符串。
        /// </summary>
        public static string AccountWin_PasswordHint {
            get {
                return ResourceManager.GetString("AccountWin_PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在进行 TCP端口 可用性检测... 的本地化字符串。
        /// </summary>
        public static string App_CheckingPort {
            get {
                return ResourceManager.GetString("App_CheckingPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前系统 TCP端口 检测正常 的本地化字符串。
        /// </summary>
        public static string App_CheckPortPassed {
            get {
                return ResourceManager.GetString("App_CheckPortPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序已关闭 的本地化字符串。
        /// </summary>
        public static string App_Close {
            get {
                return ResourceManager.GetString("App_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请不要重复打开，程序已经运行 的本地化字符串。
        /// </summary>
        public static string App_NotRunAgain {
            get {
                return ResourceManager.GetString("App_NotRunAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到 TCP端口 3216 被占用，请解除端口占用 的本地化字符串。
        /// </summary>
        public static string App_Port3216Warning {
            get {
                return ResourceManager.GetString("App_Port3216Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到 TCP端口 59743 被占用，请解除端口占用 的本地化字符串。
        /// </summary>
        public static string App_Port59743Warning {
            get {
                return ResourceManager.GetString("App_Port59743Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用 的本地化字符串。
        /// </summary>
        public static string App_Welcome {
            get {
                return ResourceManager.GetString("App_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取服务器更新版本号出现异常 的本地化字符串。
        /// </summary>
        public static string CoreApi_GetUpdateVersionException {
            get {
                return ResourceManager.GetString("CoreApi_GetUpdateVersionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取服务器更新版本号失败 的本地化字符串。
        /// </summary>
        public static string CoreApi_GetUpdateVersionFailed {
            get {
                return ResourceManager.GetString("CoreApi_GetUpdateVersionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取服务器更新版本号成功 的本地化字符串。
        /// </summary>
        public static string CoreApi_GetUpdateVersionSuccess {
            get {
                return ResourceManager.GetString("CoreApi_GetUpdateVersionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求结束，状态 的本地化字符串。
        /// </summary>
        public static string CoreApi_ResponseStatus {
            get {
                return ResourceManager.GetString("CoreApi_ResponseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求结束，状态码 的本地化字符串。
        /// </summary>
        public static string CoreApi_StatusCode {
            get {
                return ResourceManager.GetString("CoreApi_StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求超时 的本地化字符串。
        /// </summary>
        public static string CoreApi_TimedOut {
            get {
                return ResourceManager.GetString("CoreApi_TimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string DialogWin_Cancel {
            get {
                return ResourceManager.GetString("DialogWin_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string DialogWin_Enter {
            get {
                return ResourceManager.GetString("DialogWin_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求出现异常 的本地化字符串。
        /// </summary>
        public static string EaApi_Exception {
            get {
                return ResourceManager.GetString("EaApi_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 License 失败 的本地化字符串。
        /// </summary>
        public static string EaApi_GetLicenseFailed {
            get {
                return ResourceManager.GetString("EaApi_GetLicenseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 License 成功 的本地化字符串。
        /// </summary>
        public static string EaApi_GetLicenseSuccess {
            get {
                return ResourceManager.GetString("EaApi_GetLicenseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求失败，返回结果 的本地化字符串。
        /// </summary>
        public static string EaApi_RequestFailed {
            get {
                return ResourceManager.GetString("EaApi_RequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求结束，状态 的本地化字符串。
        /// </summary>
        public static string EaApi_ResponseStatus {
            get {
                return ResourceManager.GetString("EaApi_ResponseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求结束，状态码 的本地化字符串。
        /// </summary>
        public static string EaApi_StatusCode {
            get {
                return ResourceManager.GetString("EaApi_StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求超时 的本地化字符串。
        /// </summary>
        public static string EaApi_TimeOut {
            get {
                return ResourceManager.GetString("EaApi_TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EA看门狗服务已取消 的本地化字符串。
        /// </summary>
        public static string EaWatchDog_Cancellation {
            get {
                return ResourceManager.GetString("EaWatchDog_Cancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EA看门狗任务出现异常 的本地化字符串。
        /// </summary>
        public static string EaWatchDog_Exception {
            get {
                return ResourceManager.GetString("EaWatchDog_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束EADesktop进程树成功 的本地化字符串。
        /// </summary>
        public static string EaWatchDog_KillEADesktopSuccess {
            get {
                return ResourceManager.GetString("EaWatchDog_KillEADesktopSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束Origin进程树成功 的本地化字符串。
        /// </summary>
        public static string EaWatchDog_KillOriginSuccess {
            get {
                return ResourceManager.GetString("EaWatchDog_KillOriginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EA看门狗服务正在运行，请勿重复启动 的本地化字符串。
        /// </summary>
        public static string EaWatchDog_NotAgainRun {
            get {
                return ResourceManager.GetString("EaWatchDog_NotAgainRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动EA看门狗服务成功 的本地化字符串。
        /// </summary>
        public static string EaWatchDog_RunSuccess {
            get {
                return ResourceManager.GetString("EaWatchDog_RunSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止EA看门狗服务成功 的本地化字符串。
        /// </summary>
        public static string EaWatchDog_StopSuccess {
            get {
                return ResourceManager.GetString("EaWatchDog_StopSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空文件夹出现异常 的本地化字符串。
        /// </summary>
        public static string FileHelper_ClearDirectoryException {
            get {
                return ResourceManager.GetString("FileHelper_ClearDirectoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空文件夹成功 的本地化字符串。
        /// </summary>
        public static string FileHelper_ClearDirectorySuccess {
            get {
                return ResourceManager.GetString("FileHelper_ClearDirectorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取资源文件出现异常 的本地化字符串。
        /// </summary>
        public static string FileHelper_ExtractResFileException {
            get {
                return ResourceManager.GetString("FileHelper_ExtractResFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取资源文件成功 的本地化字符串。
        /// </summary>
        public static string FileHelper_ExtractResFileSuccess {
            get {
                return ResourceManager.GetString("FileHelper_ExtractResFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未发现战地1进程，操作取消 的本地化字符串。
        /// </summary>
        public static string GameUtil_IsCheckBF1NotRun {
            get {
                return ResourceManager.GetString("GameUtil_IsCheckBF1NotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战地1正在运行，请先关闭游戏 的本地化字符串。
        /// </summary>
        public static string GameUtil_IsCheckBF1Running {
            get {
                return ResourceManager.GetString("GameUtil_IsCheckBF1Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FrostyModManager正在运行，请不要重复启动 的本地化字符串。
        /// </summary>
        public static string GameUtil_IsCheckFrostyModManagerRunning {
            get {
                return ResourceManager.GetString("GameUtil_IsCheckFrostyModManagerRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FrostyModManager正在运行，请先关闭程序 的本地化字符串。
        /// </summary>
        public static string GameUtil_IsCheckFrostyModManagerRunning2 {
            get {
                return ResourceManager.GetString("GameUtil_IsCheckFrostyModManagerRunning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MarneLauncher正在运行，请不要重复启动 的本地化字符串。
        /// </summary>
        public static string GameUtil_IsCheckMarneLauncherRunning {
            get {
                return ResourceManager.GetString("GameUtil_IsCheckMarneLauncherRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已找到战地1安装路径 的本地化字符串。
        /// </summary>
        public static string Globals_BF1PathFind {
            get {
                return ResourceManager.GetString("Globals_BF1PathFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到战地1安装路径，请手动选择 的本地化字符串。
        /// </summary>
        public static string Globals_BF1PathNotFind {
            get {
                return ResourceManager.GetString("Globals_BF1PathNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始读取配置文件... 的本地化字符串。
        /// </summary>
        public static string Globals_ReadConfig {
            get {
                return ResourceManager.GetString("Globals_ReadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取配置文件成功 的本地化字符串。
        /// </summary>
        public static string Globals_ReadConfigSuccess {
            get {
                return ResourceManager.GetString("Globals_ReadConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始保存配置文件... 的本地化字符串。
        /// </summary>
        public static string Globals_SaveConfig {
            get {
                return ResourceManager.GetString("Globals_SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存配置文件成功 的本地化字符串。
        /// </summary>
        public static string Globals_SaveConfigSuccess {
            get {
                return ResourceManager.GetString("Globals_SaveConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反序列化出现异常 的本地化字符串。
        /// </summary>
        public static string JsonHelper_DeserializeException {
            get {
                return ResourceManager.GetString("JsonHelper_DeserializeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列化出现异常 的本地化字符串。
        /// </summary>
        public static string JsonHelper_SerializeException {
            get {
                return ResourceManager.GetString("JsonHelper_SerializeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战地1游戏路径为空，操作取消 的本地化字符串。
        /// </summary>
        public static string Launch_GamePathNotEmpty {
            get {
                return ResourceManager.GetString("Launch_GamePathNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动战地1游戏出现异常 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGameException {
            get {
                return ResourceManager.GetString("Launch_LaunchGameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动战地1游戏成功 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGameSuccess {
            get {
                return ResourceManager.GetString("Launch_LaunchGameSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动战地1游戏中... 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchingGame {
            get {
                return ResourceManager.GetString("Launch_LaunchingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用MOD 的本地化字符串。
        /// </summary>
        public static string LaunchView_EnabledMod {
            get {
                return ResourceManager.GetString("LaunchView_EnabledMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于安装寒霜Mod和启动战地1工具，支持多个Mod安装，支持拖拽排序，一键安装Mod无需其它繁琐操作 的本地化字符串。
        /// </summary>
        public static string LaunchView_FrostyModManagerDesc {
            get {
                return ResourceManager.GetString("LaunchView_FrostyModManagerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于启动本地战地1服务器或加入其它公共服务器，支持Mod联机，支持局域网联机 的本地化字符串。
        /// </summary>
        public static string LaunchView_MarneLauncherDesc {
            get {
                return ResourceManager.GetString("LaunchView_MarneLauncherDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        public static string LaunchView_Run {
            get {
                return ResourceManager.GetString("LaunchView_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string LaunchView_Stop {
            get {
                return ResourceManager.GetString("LaunchView_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序资源数据，初始化成功 的本地化字符串。
        /// </summary>
        public static string LoadWin_AppResourcesDataInitializeSuccess {
            get {
                return ResourceManager.GetString("LoadWin_AppResourcesDataInitializeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始初始化资源数据... 的本地化字符串。
        /// </summary>
        public static string LoadWin_BeginInitializeResources {
            get {
                return ResourceManager.GetString("LoadWin_BeginInitializeResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战地1安装磁盘格式，检查通过 的本地化字符串。
        /// </summary>
        public static string LoadWin_BF1InstallDiskCheckPassed {
            get {
                return ResourceManager.GetString("LoadWin_BF1InstallDiskCheckPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战地1安装磁盘格式不是NTFS，请转换磁盘格式 的本地化字符串。
        /// </summary>
        public static string LoadWin_BF1InstallDiskNotNTFS {
            get {
                return ResourceManager.GetString("LoadWin_BF1InstallDiskNotNTFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战地1安装路径 的本地化字符串。
        /// </summary>
        public static string LoadWin_BF1InstallPath {
            get {
                return ResourceManager.GetString("LoadWin_BF1InstallPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战地1游戏版本，检查通过 的本地化字符串。
        /// </summary>
        public static string LoadWin_BF1VersionCheckPassed {
            get {
                return ResourceManager.GetString("LoadWin_BF1VersionCheckPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端模式 的本地化字符串。
        /// </summary>
        public static string LoadWin_ClientMode {
            get {
                return ResourceManager.GetString("LoadWin_ClientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在关闭其它服务进程... 的本地化字符串。
        /// </summary>
        public static string LoadWin_ClosingOtherServiceProcess {
            get {
                return ResourceManager.GetString("LoadWin_ClosingOtherServiceProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示语言 的本地化字符串。
        /// </summary>
        public static string LoadWin_DisplayLanguage {
            get {
                return ResourceManager.GetString("LoadWin_DisplayLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在提取资源文件 Frosty.zip ... 的本地化字符串。
        /// </summary>
        public static string LoadWin_ExtractingResourceFileFrostyZip {
            get {
                return ResourceManager.GetString("LoadWin_ExtractingResourceFileFrostyZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在提取资源文件 Marne.zip ... 的本地化字符串。
        /// </summary>
        public static string LoadWin_ExtractingResourceFileMarneZip {
            get {
                return ResourceManager.GetString("LoadWin_ExtractingResourceFileMarneZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在提取资源文件 Service.zip ... 的本地化字符串。
        /// </summary>
        public static string LoadWin_ExtractingResourceFileServiceZip {
            get {
                return ResourceManager.GetString("LoadWin_ExtractingResourceFileServiceZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可执行文件 (.exe)|*.exe 的本地化字符串。
        /// </summary>
        public static string LoadWin_FileDialogFilter {
            get {
                return ResourceManager.GetString("LoadWin_FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择战地1游戏安装目录 &quot;bf1.exe&quot; 文件路径 的本地化字符串。
        /// </summary>
        public static string LoadWin_FileDialogTitle {
            get {
                return ResourceManager.GetString("LoadWin_FileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BF1游戏主程序路径，获取成功 的本地化字符串。
        /// </summary>
        public static string LoadWin_GetBF1ExePathSuccess {
            get {
                return ResourceManager.GetString("LoadWin_GetBF1ExePathSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的战地1游戏版本，请重新选择 的本地化字符串。
        /// </summary>
        public static string LoadWin_NoSupportBF1Version {
            get {
                return ResourceManager.GetString("LoadWin_NoSupportBF1Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开配置目录 的本地化字符串。
        /// </summary>
        public static string LoadWin_OpenConfigFolder {
            get {
                return ResourceManager.GetString("LoadWin_OpenConfigFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其它服务进程，关闭成功 的本地化字符串。
        /// </summary>
        public static string LoadWin_OtherServiceProcessClosedSuccess {
            get {
                return ResourceManager.GetString("LoadWin_OtherServiceProcessClosedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源文件 Frosty 检查通过 的本地化字符串。
        /// </summary>
        public static string LoadWin_ResourceFileFrostyCheckPassed {
            get {
                return ResourceManager.GetString("LoadWin_ResourceFileFrostyCheckPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源文件 Marne 检查通过 的本地化字符串。
        /// </summary>
        public static string LoadWin_ResourceFileMarneCheckPassed {
            get {
                return ResourceManager.GetString("LoadWin_ResourceFileMarneCheckPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源文件 Service 检查通过 的本地化字符串。
        /// </summary>
        public static string LoadWin_ResourceFileServiceCheckPassed {
            get {
                return ResourceManager.GetString("LoadWin_ResourceFileServiceCheckPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源初始化时出现异常 的本地化字符串。
        /// </summary>
        public static string LoadWin_ResourceInitializeException {
            get {
                return ResourceManager.GetString("LoadWin_ResourceInitializeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动主程序 的本地化字符串。
        /// </summary>
        public static string LoadWin_RunMainApp {
            get {
                return ResourceManager.GetString("LoadWin_RunMainApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择战地1游戏安装目录 &quot;bf1.exe&quot; 文件路径 的本地化字符串。
        /// </summary>
        public static string LoadWin_SelectBF1InstallPath {
            get {
                return ResourceManager.GetString("LoadWin_SelectBF1InstallPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择战地1安装路径时出现异常 的本地化字符串。
        /// </summary>
        public static string LoadWin_SelectBF1PathException {
            get {
                return ResourceManager.GetString("LoadWin_SelectBF1PathException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择BF1路径 的本地化字符串。
        /// </summary>
        public static string LoadWin_SelectPath {
            get {
                return ResourceManager.GetString("LoadWin_SelectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务端模式 的本地化字符串。
        /// </summary>
        public static string LoadWin_ServerMode {
            get {
                return ResourceManager.GetString("LoadWin_ServerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在解压文件 Frosty.zip ... 的本地化字符串。
        /// </summary>
        public static string LoadWin_UnzippingTheFileFrostyZip {
            get {
                return ResourceManager.GetString("LoadWin_UnzippingTheFileFrostyZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在解压文件 Marne.zip ... 的本地化字符串。
        /// </summary>
        public static string LoadWin_UnzippingTheFileMarneZip {
            get {
                return ResourceManager.GetString("LoadWin_UnzippingTheFileMarneZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在解压文件 Service.zip ... 的本地化字符串。
        /// </summary>
        public static string LoadWin_UnzippingTheFileServiceZip {
            get {
                return ResourceManager.GetString("LoadWin_UnzippingTheFileServiceZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 官网 的本地化字符串。
        /// </summary>
        public static string LoadWin_Website {
            get {
                return ResourceManager.GetString("LoadWin_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作模式 的本地化字符串。
        /// </summary>
        public static string LoadWin_WorkMode {
            get {
                return ResourceManager.GetString("LoadWin_WorkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阿拉伯语 的本地化字符串。
        /// </summary>
        public static string LocaleWin_Arabic {
            get {
                return ResourceManager.GetString("LocaleWin_Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战地1语言 的本地化字符串。
        /// </summary>
        public static string LocaleWin_BF1Language {
            get {
                return ResourceManager.GetString("LocaleWin_BF1Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改BF1注册表语言信息时出现异常 的本地化字符串。
        /// </summary>
        public static string LocaleWin_ChangeBF1RegLangInfoException {
            get {
                return ResourceManager.GetString("LocaleWin_ChangeBF1RegLangInfoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改战地1注册表语言信息成功 的本地化字符串。
        /// </summary>
        public static string LocaleWin_ChangeBF1RegLangInfoSuccess {
            get {
                return ResourceManager.GetString("LocaleWin_ChangeBF1RegLangInfoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改语言 的本地化字符串。
        /// </summary>
        public static string LocaleWin_ChangeLanguage {
            get {
                return ResourceManager.GetString("LocaleWin_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英语 的本地化字符串。
        /// </summary>
        public static string LocaleWin_English {
            get {
                return ResourceManager.GetString("LocaleWin_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 法语 的本地化字符串。
        /// </summary>
        public static string LocaleWin_French {
            get {
                return ResourceManager.GetString("LocaleWin_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 德语 的本地化字符串。
        /// </summary>
        public static string LocaleWin_German {
            get {
                return ResourceManager.GetString("LocaleWin_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取BF1注册表语言信息时出现异常 的本地化字符串。
        /// </summary>
        public static string LocaleWin_GetBF1RegLangInfoException {
            get {
                return ResourceManager.GetString("LocaleWin_GetBF1RegLangInfoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取BF1注册表语言信息成功 的本地化字符串。
        /// </summary>
        public static string LocaleWin_GetBF1RegLangInfoSuccess {
            get {
                return ResourceManager.GetString("LocaleWin_GetBF1RegLangInfoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意大利语 的本地化字符串。
        /// </summary>
        public static string LocaleWin_Italian {
            get {
                return ResourceManager.GetString("LocaleWin_Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日语 的本地化字符串。
        /// </summary>
        public static string LocaleWin_Japanese {
            get {
                return ResourceManager.GetString("LocaleWin_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到战地1注册表语言信息 的本地化字符串。
        /// </summary>
        public static string LocaleWin_NotFoundBF1RegLangInfo {
            get {
                return ResourceManager.GetString("LocaleWin_NotFoundBF1RegLangInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家未选择战地1语言信息，操作取消 的本地化字符串。
        /// </summary>
        public static string LocaleWin_PlayerNotSelectBF1LangInfoTaskCanceled {
            get {
                return ResourceManager.GetString("LocaleWin_PlayerNotSelectBF1LangInfoTaskCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波兰语 的本地化字符串。
        /// </summary>
        public static string LocaleWin_Polish {
            get {
                return ResourceManager.GetString("LocaleWin_Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 葡萄牙语 - 巴西 的本地化字符串。
        /// </summary>
        public static string LocaleWin_PortugueseBrazil {
            get {
                return ResourceManager.GetString("LocaleWin_PortugueseBrazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 俄语 的本地化字符串。
        /// </summary>
        public static string LocaleWin_Russian {
            get {
                return ResourceManager.GetString("LocaleWin_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 西班牙语 - 墨西哥 的本地化字符串。
        /// </summary>
        public static string LocaleWin_SpanishMexico {
            get {
                return ResourceManager.GetString("LocaleWin_SpanishMexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 西班牙语 - 西班牙 的本地化字符串。
        /// </summary>
        public static string LocaleWin_SpanishSpain {
            get {
                return ResourceManager.GetString("LocaleWin_SpanishSpain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 繁体中文 的本地化字符串。
        /// </summary>
        public static string LocaleWin_TChinese {
            get {
                return ResourceManager.GetString("LocaleWin_TChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 土耳其语 的本地化字符串。
        /// </summary>
        public static string LocaleWin_Turkish {
            get {
                return ResourceManager.GetString("LocaleWin_Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理 Local HTTP 请求出现异常 的本地化字符串。
        /// </summary>
        public static string LocalHttpServer_HandleRequestException {
            get {
                return ResourceManager.GetString("LocalHttpServer_HandleRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local HTTP 服务正在运行，请勿重复启动 的本地化字符串。
        /// </summary>
        public static string LocalHttpServer_NotAgainRun {
            get {
                return ResourceManager.GetString("LocalHttpServer_NotAgainRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到 Local HTTP GET请求 的本地化字符串。
        /// </summary>
        public static string LocalHttpServer_ReceiveGetRequest {
            get {
                return ResourceManager.GetString("LocalHttpServer_ReceiveGetRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到 Local HTTP POST请求 的本地化字符串。
        /// </summary>
        public static string LocalHttpServer_ReceivePostRequest {
            get {
                return ResourceManager.GetString("LocalHttpServer_ReceivePostRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求的客户端为 的本地化字符串。
        /// </summary>
        public static string LocalHttpServer_RequestInfo {
            get {
                return ResourceManager.GetString("LocalHttpServer_RequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 Local HTTP 服务成功 的本地化字符串。
        /// </summary>
        public static string LocalHttpServer_RunSuccess {
            get {
                return ResourceManager.GetString("LocalHttpServer_RunSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 Local HTTP 服务成功 的本地化字符串。
        /// </summary>
        public static string LocalHttpServer_StopSuccess {
            get {
                return ResourceManager.GetString("LocalHttpServer_StopSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级 的本地化字符串。
        /// </summary>
        public static string LogView_Level {
            get {
                return ResourceManager.GetString("LogView_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string LogView_Message {
            get {
                return ResourceManager.GetString("LogView_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string LogView_Time {
            get {
                return ResourceManager.GetString("LogView_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异步读取 TCP 字符串时出现异常 的本地化字符串。
        /// </summary>
        public static string LSXTcpServer_AsyncReadStringException {
            get {
                return ResourceManager.GetString("LSXTcpServer_AsyncReadStringException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本次启动 ContentId 为 的本地化字符串。
        /// </summary>
        public static string LSXTcpServer_ContentId {
            get {
                return ResourceManager.GetString("LSXTcpServer_ContentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理 TCP Battlelog 客户端连接出现超时异常 的本地化字符串。
        /// </summary>
        public static string LSXTcpServer_HandleClientBattlelogConnectException {
            get {
                return ResourceManager.GetString("LSXTcpServer_HandleClientBattlelogConnectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理 TCP 客户端连接出现异常 的本地化字符串。
        /// </summary>
        public static string LSXTcpServer_HandleClientConnectException {
            get {
                return ResourceManager.GetString("LSXTcpServer_HandleClientConnectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在处理启动游戏请求... 的本地化字符串。
        /// </summary>
        public static string LSXTcpServer_HandleLaunch {
            get {
                return ResourceManager.GetString("LSXTcpServer_HandleLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LSX 服务正在运行，请勿重复启动 的本地化字符串。
        /// </summary>
        public static string LSXTcpServer_NotAgainRun {
            get {
                return ResourceManager.GetString("LSXTcpServer_NotAgainRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 LSX 服务成功 的本地化字符串。
        /// </summary>
        public static string LSXTcpServer_RunSuccess {
            get {
                return ResourceManager.GetString("LSXTcpServer_RunSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 LSX 服务成功 的本地化字符串。
        /// </summary>
        public static string LSXTcpServer_StopSuccess {
            get {
                return ResourceManager.GetString("LSXTcpServer_StopSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告: 战地1游戏客户端已被关闭 的本地化字符串。
        /// </summary>
        public static string LSXTcpServer_WarnGameClose {
            get {
                return ResourceManager.GetString("LSXTcpServer_WarnGameClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本，请下载更新 的本地化字符串。
        /// </summary>
        public static string MainWin_CheckNeedUpdate {
            get {
                return ResourceManager.GetString("MainWin_CheckNeedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在检测新版本中... 的本地化字符串。
        /// </summary>
        public static string MainWin_CheckNewVersion {
            get {
                return ResourceManager.GetString("MainWin_CheckNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你当前使用的已是最新版本 的本地化字符串。
        /// </summary>
        public static string MainWin_CheckNoUpdate {
            get {
                return ResourceManager.GetString("MainWin_CheckNoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测新版本失败，请检查网络连接 的本地化字符串。
        /// </summary>
        public static string MainWin_CheckUpdateFailed {
            get {
                return ResourceManager.GetString("MainWin_CheckUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测新版本失败，重试中... 的本地化字符串。
        /// </summary>
        public static string MainWin_CheckUpdateRetry {
            get {
                return ResourceManager.GetString("MainWin_CheckUpdateRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭主程序成功 的本地化字符串。
        /// </summary>
        public static string MainWin_CloseSuccess {
            get {
                return ResourceManager.GetString("MainWin_CloseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载新版本 的本地化字符串。
        /// </summary>
        public static string MainWin_DownloadUpdate {
            get {
                return ResourceManager.GetString("MainWin_DownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出程序 的本地化字符串。
        /// </summary>
        public static string MainWin_ExitApp {
            get {
                return ResourceManager.GetString("MainWin_ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可通过托盘右键菜单完全退出程序 的本地化字符串。
        /// </summary>
        public static string MainWin_NotifyBalloonMsg {
            get {
                return ResourceManager.GetString("MainWin_NotifyBalloonMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开战地1目录 的本地化字符串。
        /// </summary>
        public static string MainWin_OpenBF1Folder {
            get {
                return ResourceManager.GetString("MainWin_OpenBF1Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开配置目录 的本地化字符串。
        /// </summary>
        public static string MainWin_OpenConfigFolder {
            get {
                return ResourceManager.GetString("MainWin_OpenConfigFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开Crash目录 的本地化字符串。
        /// </summary>
        public static string MainWin_OpenCrashFolder {
            get {
                return ResourceManager.GetString("MainWin_OpenCrashFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开Marne目录 的本地化字符串。
        /// </summary>
        public static string MainWin_OpenMarneFolder {
            get {
                return ResourceManager.GetString("MainWin_OpenMarneFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动主程序成功 的本地化字符串。
        /// </summary>
        public static string MainWin_RunMainAppSuccess {
            get {
                return ResourceManager.GetString("MainWin_RunMainAppSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置游戏语言 的本地化字符串。
        /// </summary>
        public static string MainWin_SetGameLanguage {
            get {
                return ResourceManager.GetString("MainWin_SetGameLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置启动账号 的本地化字符串。
        /// </summary>
        public static string MainWin_SetLaunchAccount {
            get {
                return ResourceManager.GetString("MainWin_SetLaunchAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示主窗口 的本地化字符串。
        /// </summary>
        public static string MainWin_ShowWindow {
            get {
                return ResourceManager.GetString("MainWin_ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加地图 的本地化字符串。
        /// </summary>
        public static string MapWin_AddMap {
            get {
                return ResourceManager.GetString("MapWin_AddMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空地图列表 的本地化字符串。
        /// </summary>
        public static string MapWin_ClearMapList {
            get {
                return ResourceManager.GetString("MapWin_ClearMapList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除地图 的本地化字符串。
        /// </summary>
        public static string MapWin_DeleteMap {
            get {
                return ResourceManager.GetString("MapWin_DeleteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化地图列表出现异常 的本地化字符串。
        /// </summary>
        public static string MapWin_InitMapException {
            get {
                return ResourceManager.GetString("MapWin_InitMapException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图列表文件路径为 的本地化字符串。
        /// </summary>
        public static string MapWin_MapListPath {
            get {
                return ResourceManager.GetString("MapWin_MapListPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存地图列表 的本地化字符串。
        /// </summary>
        public static string MapWin_SaveMapList {
            get {
                return ResourceManager.GetString("MapWin_SaveMapList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存地图列表出现异常 的本地化字符串。
        /// </summary>
        public static string MapWin_SaveMapListException {
            get {
                return ResourceManager.GetString("MapWin_SaveMapListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存地图列表成功 的本地化字符串。
        /// </summary>
        public static string MapWin_SaveMapSuccess {
            get {
                return ResourceManager.GetString("MapWin_SaveMapSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 崩溃时间 的本地化字符串。
        /// </summary>
        public static string MiscUtil_CrashTime {
            get {
                return ResourceManager.GetString("MiscUtil_CrashTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常信息 的本地化字符串。
        /// </summary>
        public static string MiscUtil_ExceptionMsg {
            get {
                return ResourceManager.GetString("MiscUtil_ExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常类型 的本地化字符串。
        /// </summary>
        public static string MiscUtil_ExceptionType {
            get {
                return ResourceManager.GetString("MiscUtil_ExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电脑名称 的本地化字符串。
        /// </summary>
        public static string MiscUtil_MachineName {
            get {
                return ResourceManager.GetString("MiscUtil_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行库版本 的本地化字符串。
        /// </summary>
        public static string MiscUtil_OSArchitecture {
            get {
                return ResourceManager.GetString("MiscUtil_OSArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统版本 的本地化字符串。
        /// </summary>
        public static string MiscUtil_OSVersion {
            get {
                return ResourceManager.GetString("MiscUtil_OSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行库环境 的本地化字符串。
        /// </summary>
        public static string MiscUtil_RuntimeIdentifier {
            get {
                return ResourceManager.GetString("MiscUtil_RuntimeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行库平台 的本地化字符串。
        /// </summary>
        public static string MiscUtil_RuntimeVersion {
            get {
                return ResourceManager.GetString("MiscUtil_RuntimeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 堆栈调用 的本地化字符串。
        /// </summary>
        public static string MiscUtil_StackTrace {
            get {
                return ResourceManager.GetString("MiscUtil_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统目录 的本地化字符串。
        /// </summary>
        public static string MiscUtil_SystemDirectory {
            get {
                return ResourceManager.GetString("MiscUtil_SystemDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未处理异常 的本地化字符串。
        /// </summary>
        public static string MiscUtil_UnhandledException {
            get {
                return ResourceManager.GetString("MiscUtil_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名称 的本地化字符串。
        /// </summary>
        public static string MiscUtil_UserName {
            get {
                return ResourceManager.GetString("MiscUtil_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序版本 的本地化字符串。
        /// </summary>
        public static string MiscUtil_VersionInfo {
            get {
                return ResourceManager.GetString("MiscUtil_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空旧版Mod文件成功 的本地化字符串。
        /// </summary>
        public static string ModWin_ClearOldMods {
            get {
                return ResourceManager.GetString("ModWin_ClearOldMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寒霜Mod文件 (.fbmod)|*.fbmod 的本地化字符串。
        /// </summary>
        public static string ModWin_FileDialogFilter {
            get {
                return ResourceManager.GetString("ModWin_FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要安装的战地1寒霜Mod文件（支持多选） 的本地化字符串。
        /// </summary>
        public static string ModWin_FileDialogTitle {
            get {
                return ResourceManager.GetString("ModWin_FileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径 的本地化字符串。
        /// </summary>
        public static string ModWin_FilePath {
            get {
                return ResourceManager.GetString("ModWin_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装MOD并启动战地1游戏 的本地化字符串。
        /// </summary>
        public static string ModWin_InstallModAndRunBF1Game {
            get {
                return ResourceManager.GetString("ModWin_InstallModAndRunBF1Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装MOD列表 的本地化字符串。
        /// </summary>
        public static string ModWin_InstallModList {
            get {
                return ResourceManager.GetString("ModWin_InstallModList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装Mod出现异常 的本地化字符串。
        /// </summary>
        public static string ModWin_InstallModsException {
            get {
                return ResourceManager.GetString("ModWin_InstallModsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改日期 的本地化字符串。
        /// </summary>
        public static string ModWin_LastWriteTime {
            get {
                return ResourceManager.GetString("ModWin_LastWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动FrostyModManager中... 的本地化字符串。
        /// </summary>
        public static string ModWin_LaunchFrostyModManager {
            get {
                return ResourceManager.GetString("ModWin_LaunchFrostyModManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取Mod配置信息出现异常 的本地化字符串。
        /// </summary>
        public static string ModWin_ReadConfigException {
            get {
                return ResourceManager.GetString("ModWin_ReadConfigException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择MOD 的本地化字符串。
        /// </summary>
        public static string ModWin_SelectMods {
            get {
                return ResourceManager.GetString("ModWin_SelectMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择安装Mods出现异常 的本地化字符串。
        /// </summary>
        public static string ModWin_SelectModsException {
            get {
                return ResourceManager.GetString("ModWin_SelectModsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        public static string ModWin_Size {
            get {
                return ResourceManager.GetString("ModWin_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入FrostyModManager配置文件成功 的本地化字符串。
        /// </summary>
        public static string ModWin_WriteConfigFrostyModManager {
            get {
                return ResourceManager.GetString("ModWin_WriteConfigFrostyModManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string MsgBoxHelper_Error {
            get {
                return ResourceManager.GetString("MsgBoxHelper_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        public static string MsgBoxHelper_Exception {
            get {
                return ResourceManager.GetString("MsgBoxHelper_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生了未知的异常，查看异常提示以获取更多信息\n\n异常消息:\n 的本地化字符串。
        /// </summary>
        public static string MsgBoxHelper_ExceptionMsg {
            get {
                return ResourceManager.GetString("MsgBoxHelper_ExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string MsgBoxHelper_Information {
            get {
                return ResourceManager.GetString("MsgBoxHelper_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string MsgBoxHelper_Warning {
            get {
                return ResourceManager.GetString("MsgBoxHelper_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改玩家名称 的本地化字符串。
        /// </summary>
        public static string NameView_ChangePlayerName {
            get {
                return ResourceManager.GetString("NameView_ChangePlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改玩家名称出现异常 的本地化字符串。
        /// </summary>
        public static string NameView_ChangePlayerNameException {
            get {
                return ResourceManager.GetString("NameView_ChangePlayerNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化自定义玩家名称出现异常 的本地化字符串。
        /// </summary>
        public static string NameView_InitializePlayerNameException {
            get {
                return ResourceManager.GetString("NameView_InitializePlayerNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改玩家名称成功，请启动游戏查看 的本地化字符串。
        /// </summary>
        public static string NameView_PlayerNameChangeSuccess {
            get {
                return ResourceManager.GetString("NameView_PlayerNameChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入自定义玩家名称 的本地化字符串。
        /// </summary>
        public static string NameView_PlayerNameHint {
            get {
                return ResourceManager.GetString("NameView_PlayerNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家名称不能超过15字节，请重新修改 的本地化字符串。
        /// </summary>
        public static string NameView_PlayerNameMax15Bytes {
            get {
                return ResourceManager.GetString("NameView_PlayerNameMax15Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家名称不能为空，请重新修改 的本地化字符串。
        /// </summary>
        public static string NameView_PlayerNameNoEmpty {
            get {
                return ResourceManager.GetString("NameView_PlayerNameNoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 官网 的本地化字符串。
        /// </summary>
        public static string NameView_Website {
            get {
                return ResourceManager.GetString("NameView_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string NotifierHelper_Error {
            get {
                return ResourceManager.GetString("NotifierHelper_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string NotifierHelper_Information {
            get {
                return ResourceManager.GetString("NotifierHelper_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知 的本地化字符串。
        /// </summary>
        public static string NotifierHelper_Notification {
            get {
                return ResourceManager.GetString("NotifierHelper_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string NotifierHelper_Success {
            get {
                return ResourceManager.GetString("NotifierHelper_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string NotifierHelper_Warning {
            get {
                return ResourceManager.GetString("NotifierHelper_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭进程出现异常 的本地化字符串。
        /// </summary>
        public static string ProcessHelper_CloseProcessException {
            get {
                return ResourceManager.GetString("ProcessHelper_CloseProcessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到进程信息 的本地化字符串。
        /// </summary>
        public static string ProcessHelper_CloseProcessNotFound {
            get {
                return ResourceManager.GetString("ProcessHelper_CloseProcessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭进程成功 的本地化字符串。
        /// </summary>
        public static string ProcessHelper_CloseProcessSuccess {
            get {
                return ResourceManager.GetString("ProcessHelper_CloseProcessSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接不是http格式 的本地化字符串。
        /// </summary>
        public static string ProcessHelper_HttpFormatError {
            get {
                return ResourceManager.GetString("ProcessHelper_HttpFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件夹出现异常 的本地化字符串。
        /// </summary>
        public static string ProcessHelper_OpenDirectoryException {
            get {
                return ResourceManager.GetString("ProcessHelper_OpenDirectoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹路径不存在 的本地化字符串。
        /// </summary>
        public static string ProcessHelper_OpenDirectoryNotExists {
            get {
                return ResourceManager.GetString("ProcessHelper_OpenDirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开http链接出现异常 的本地化字符串。
        /// </summary>
        public static string ProcessHelper_OpenHttpException {
            get {
                return ResourceManager.GetString("ProcessHelper_OpenHttpException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动程序出现异常 的本地化字符串。
        /// </summary>
        public static string ProcessHelper_OpenProcessException {
            get {
                return ResourceManager.GetString("ProcessHelper_OpenProcessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序路径不存在 的本地化字符串。
        /// </summary>
        public static string ProcessHelper_OpenProcessNotExists {
            get {
                return ResourceManager.GetString("ProcessHelper_OpenProcessNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动程序成功 的本地化字符串。
        /// </summary>
        public static string ProcessHelper_OpenProcessSuccess {
            get {
                return ResourceManager.GetString("ProcessHelper_OpenProcessSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动EA看门狗服务... 的本地化字符串。
        /// </summary>
        public static string Ready_RunEaWatchDogService {
            get {
                return ResourceManager.GetString("Ready_RunEaWatchDogService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动 Local HTTP 服务... 的本地化字符串。
        /// </summary>
        public static string Ready_RunLocalHttpService {
            get {
                return ResourceManager.GetString("Ready_RunLocalHttpService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动 LSX 服务... 的本地化字符串。
        /// </summary>
        public static string Ready_RunLSXService {
            get {
                return ResourceManager.GetString("Ready_RunLSXService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动服务进程... 的本地化字符串。
        /// </summary>
        public static string Ready_RunService {
            get {
                return ResourceManager.GetString("Ready_RunService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动核心服务出现异常 的本地化字符串。
        /// </summary>
        public static string Ready_RunServiceException {
            get {
                return ResourceManager.GetString("Ready_RunServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在停止EA看门狗服务... 的本地化字符串。
        /// </summary>
        public static string Ready_StopEaWatchDogService {
            get {
                return ResourceManager.GetString("Ready_StopEaWatchDogService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在停止 Local HTTP 服务... 的本地化字符串。
        /// </summary>
        public static string Ready_StopLocalHttpService {
            get {
                return ResourceManager.GetString("Ready_StopLocalHttpService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在停止 LSX 服务... 的本地化字符串。
        /// </summary>
        public static string Ready_StopLSXService {
            get {
                return ResourceManager.GetString("Ready_StopLSXService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止核心服务出现异常 的本地化字符串。
        /// </summary>
        public static string Ready_StopServiceException {
            get {
                return ResourceManager.GetString("Ready_StopServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取注册表出现异常 的本地化字符串。
        /// </summary>
        public static string RegistryHelper_ReadException {
            get {
                return ResourceManager.GetString("RegistryHelper_ReadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入注册表 EADesktop 虚拟安装路径出现异常 的本地化字符串。
        /// </summary>
        public static string RegistryHelper_WriteEADesktopVirtualRegException {
            get {
                return ResourceManager.GetString("RegistryHelper_WriteEADesktopVirtualRegException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入注册表 EADesktop 虚拟安装路径成功 的本地化字符串。
        /// </summary>
        public static string RegistryHelper_WriteEADesktopVirtualRegSuccess {
            get {
                return ResourceManager.GetString("RegistryHelper_WriteEADesktopVirtualRegSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入注册表出现异常 的本地化字符串。
        /// </summary>
        public static string RegistryHelper_WriteException {
            get {
                return ResourceManager.GetString("RegistryHelper_WriteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化服务器设置出现异常 的本地化字符串。
        /// </summary>
        public static string SettingWin_InitSettingException {
            get {
                return ResourceManager.GetString("SettingWin_InitSettingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取设置 的本地化字符串。
        /// </summary>
        public static string SettingWin_ReadSetting {
            get {
                return ResourceManager.GetString("SettingWin_ReadSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取服务器设置出现异常 的本地化字符串。
        /// </summary>
        public static string SettingWin_ReadSettingException {
            get {
                return ResourceManager.GetString("SettingWin_ReadSettingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取服务器设置成功 的本地化字符串。
        /// </summary>
        public static string SettingWin_ReadSettingSuccess {
            get {
                return ResourceManager.GetString("SettingWin_ReadSettingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存设置 的本地化字符串。
        /// </summary>
        public static string SettingWin_SaveSetting {
            get {
                return ResourceManager.GetString("SettingWin_SaveSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存服务器设置出现异常 的本地化字符串。
        /// </summary>
        public static string SettingWin_SaveSettingException {
            get {
                return ResourceManager.GetString("SettingWin_SaveSettingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存服务器设置成功 的本地化字符串。
        /// </summary>
        public static string SettingWin_SaveSettingSuccess {
            get {
                return ResourceManager.GetString("SettingWin_SaveSettingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器设置文件路径为 的本地化字符串。
        /// </summary>
        public static string SettingWin_SettingPath {
            get {
                return ResourceManager.GetString("SettingWin_SettingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用默认设置 的本地化字符串。
        /// </summary>
        public static string SettingWin_UseDefaultSetting {
            get {
                return ResourceManager.GetString("SettingWin_UseDefaultSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理Mod数据 的本地化字符串。
        /// </summary>
        public static string ToolsView_ClearModData {
            get {
                return ResourceManager.GetString("ToolsView_ClearModData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理Mod数据出现异常 的本地化字符串。
        /// </summary>
        public static string ToolsView_ClearModDataException {
            get {
                return ResourceManager.GetString("ToolsView_ClearModDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未发现战地1Mod数据文件夹，操作取消 的本地化字符串。
        /// </summary>
        public static string ToolsView_ClearModDataNotFound {
            get {
                return ResourceManager.GetString("ToolsView_ClearModDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理Mod数据操作成功 的本地化字符串。
        /// </summary>
        public static string ToolsView_ClearModDataSuccess {
            get {
                return ResourceManager.GetString("ToolsView_ClearModDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要清理《战地1》Mod数据吗？ 的本地化字符串。
        /// </summary>
        public static string ToolsView_ClearModDataWarning {
            get {
                return ResourceManager.GetString("ToolsView_ClearModDataWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑地图列表 的本地化字符串。
        /// </summary>
        public static string ToolsView_EditMapList {
            get {
                return ResourceManager.GetString("ToolsView_EditMapList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑服务器设置 的本地化字符串。
        /// </summary>
        public static string ToolsView_EditServerSettings {
            get {
                return ResourceManager.GetString("ToolsView_EditServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP重定向 的本地化字符串。
        /// </summary>
        public static string ToolsView_IPRedirect {
            get {
                return ResourceManager.GetString("ToolsView_IPRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束战地1进程 的本地化字符串。
        /// </summary>
        public static string ToolsView_KillBF1Process {
            get {
                return ResourceManager.GetString("ToolsView_KillBF1Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束战地1进程操作成功 的本地化字符串。
        /// </summary>
        public static string ToolsView_KillBF1ProcessSuccess {
            get {
                return ResourceManager.GetString("ToolsView_KillBF1ProcessSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要结束《战地1》进程吗？ 的本地化字符串。
        /// </summary>
        public static string ToolsView_KillBf1ProcessWarning {
            get {
                return ResourceManager.GetString("ToolsView_KillBf1ProcessWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示FPS 的本地化字符串。
        /// </summary>
        public static string ToolsView_ShowFPS {
            get {
                return ResourceManager.GetString("ToolsView_ShowFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string ToolsView_Warning {
            get {
                return ResourceManager.GetString("ToolsView_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战地1马恩工具箱 的本地化字符串。
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
